name: macOS CI

on:
  pull_request:
    paths:
      - '**.c'
      - '**.h'
      - '**.i'
      - '**.in'
      - '**.sh'
      - '**.py'
      - '**.go'
      - '**.java'
      - '**.rb'
      - .github/workflows/macos.yml
  push:


permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  build:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
    - run: .github/build.sh macos
    - uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2.3.1
      with:
        name: openpace-dmg
        path:
          openpace*.dmg
